### ISSUE TITLE
Update README with Camunda Community Hub badges

### ISSUE THREAD

**Issue by xomiamoore** [camunda-community-hub/camunda-community-helm#50]
Hello!

Could you please add the appropriate label for lifecycle stage? You can find these badges and more information [here in our documentation](https://github.com/Camunda-Community-Hub/community/blob/main/extension-lifecycle.md).

Please let me know if I can help with any of these changes, thank you!

**Comment by aabouzaid** [comment]
@xomiamoore [done](https://github.com/camunda-community-hub/camunda-community-helm/commit/9f81797721252c2e89754851b791b6b8376f0572) :heavy_check_mark:

**Comment by xomiamoore** [comment]
Thank you so much!
